import { createReadStream } from 'node:fs';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { Injectable, Logger } from '@nestjs/common';
import type { StoragePort, StoredObject, StoredRange } from './storage.port';

/**
 * Files on the API container's own disk (docs/65 §4.1).
 *
 * For development and tests. It is **not durable** — a container restart on
 * most hosts loses everything — and `StorageModule` refuses to select it in
 * production for that reason. A photograph a customer consented to give once,
 * silently lost on a redeploy, is worse than one that was never taken.
 */
@Injectable()
export class LocalDiskAdapter implements StoragePort {
  readonly name = 'local-disk';
  readonly durable = false;
  private readonly logger = new Logger(LocalDiskAdapter.name);
  private readonly root = process.env.AVIORA_STORAGE_DIR ?? '/tmp/aviora-storage';

  private pathFor(key: string): string {
    // Keys are generated by this codebase, never by a caller — but a `..` that
    // reached here would write outside the root, so it is refused rather than
    // trusted.
    if (key.includes('..') || path.isAbsolute(key)) {
      throw new Error(`refusing a storage key that escapes the root: ${key}`);
    }
    return path.join(this.root, key);
  }

  async put(input: { key: string; body: Buffer; contentType: string }): Promise<void> {
    const file = this.pathFor(input.key);
    await fs.mkdir(path.dirname(file), { recursive: true });
    await fs.writeFile(file, input.body);
    await fs.writeFile(`${file}.type`, input.contentType, 'utf8');
  }

  async get(key: string): Promise<StoredObject | null> {
    const file = this.pathFor(key);
    try {
      const [body, contentType] = await Promise.all([
        fs.readFile(file),
        fs.readFile(`${file}.type`, 'utf8').catch(() => 'application/octet-stream'),
      ]);
      return { body, contentType };
    } catch {
      return null;
    }
  }

  /**
   * A bounded read stream (docs/73 §7). `end` is inclusive here and in
   * `createReadStream`, which is the one place the two conventions agree, so no
   * arithmetic is needed and none is done.
   */
  async getRange(
    key: string,
    range?: { start: number; end?: number },
  ): Promise<StoredRange | null> {
    const file = this.pathFor(key);
    let totalLength: number;
    try {
      totalLength = (await fs.stat(file)).size;
    } catch {
      return null;
    }
    const contentType = await fs
      .readFile(`${file}.type`, 'utf8')
      .catch(() => 'application/octet-stream');

    const start = range?.start ?? 0;
    // An open-ended range runs to the last byte; `end` is inclusive, so the
    // final index is one below the length.
    const end = Math.min(range?.end ?? totalLength - 1, totalLength - 1);
    if (start > end || start >= totalLength) return null;

    return {
      stream: createReadStream(file, { start, end }),
      contentType,
      contentLength: end - start + 1,
      totalLength,
    };
  }

  async delete(key: string): Promise<void> {
    const file = this.pathFor(key);
    // Missing is the desired end state, so a missing file is success. Consent
    // withdrawal must not fail because somebody already tidied up.
    await fs.rm(file, { force: true });
    await fs.rm(`${file}.type`, { force: true });
    this.logger.debug(`deleted ${key}`);
  }
}
